### ISSUE TITLE
Can I add private_ranges?

### ISSUE THREAD

**Issue by jyncus** [fvbommel/caddy-combine-ip-ranges#1]
Is it possible to make a configuration that combines cloudflare, dns cloudflared, and private_ranges?  

`trusted_proxies combine {
			cloudflare
			dns cloudflared
			private_ranges
		}`

When I attempt this configuration, I get "caddy module not registered: http.ip_sources.private_ranges" in the logs.

**Comment by fvbommel** [comment]
`private_ranges` is not actually an IP range module, instead it's a token that happens to have a special meaning to a few built-in modules, including the `static` IP range module:

```caddyfile
trusted_proxies combine {
	cloudflare
	dns cloudflared
	static private_ranges
}
```

I've also added this section to the README:

[This Caddy documentation page](https://caddyserver.com/docs/json/apps/http/servers/trusted_proxies/combine/parts/) lists all known modules that should theoretically work as sub-directives of this one, though not all of those have been tested in that configuration.
